Task3
postgred/myrubycource pull request #2
Opened 2016-09-16 20:54 UTC by postgred

2016-09-16 21:03 UTC, zverok commented on movies.rb
> +films.sort_by! { |film| film[:duration] }
Мы в большинстве случаев предпочитаем:
а) не использовать методов с `!` (лучше получить новую переменную, чем поменять существующую, более хороший стиль)
б) накапливать методы в цепочки — т.е. `что-то.отсортировать.взять_несколько.и т.д`

2016-09-16 21:05 UTC, zverok commented on movies.rb
>  end
Хм, упустил что `map` ты всё ещё используешь не наилучшим образом :) идея в том, что `map` превращает одну последовательность в другую, и так помогает лучше выразить намерения, т.е. `films = ...map do ... end` чётко сообщает: «мы получаем фильмы, отобразив каждую строку файла в фильм таким-то способом»

2016-09-16 21:05 UTC, zverok commented on movies.rb
> +print_films(films.reverse[0..4])
Когда ты берёшь _первые_ (или последние) элементы массива, и нужны тебе именно они, то `first(5)` лучше обозначает намерения.

2016-09-16 21:06 UTC, zverok commented on movies.rb
> +print_films(films[0..9])
Ээээ а где отбор только комедий?..

2016-09-16 21:06 UTC, zverok commented on movies.rb
> +producers.sort_by { |man| man.split(' ')[-1] }.uniq.map { |man| puts man }
Можно проще (с учётом всего сказанного выше)

2016-09-16 21:06 UTC, zverok requested changes

2016-09-16 21:09 UTC, postgred commented on movies.rb
> +print_films(films[0..9])
он как бы был, но в ходе рефакторинга я его случайно стер :)

2016-09-17 09:06 UTC, zverok commented on movies.rb
> +print_films(films.sort_by{ |film| film[:genre].include?("Camedy") }.sort_by { |film| film[:date] }.first(10))
Нет, сортировка неподходящая метафора здесь :) Проверь, что оно выдаёт — разве 10 первых комедий?

2016-09-17 09:06 UTC, zverok commented on movies.rb
> +producers = films.map { |film| film[:producer] }.sort_by { |man| man.split(' ')[-1] }.uniq
Угу. Но `.last` читабельнее чем `[-1]`

2016-09-17 09:07 UTC, zverok requested changes

2016-09-17 09:52 UTC, postgred commented on movies.rb
> +print_films(films.sort_by{ |film| film[:genre].include?("Camedy") }.sort_by { |film| film[:date] }.first(10))
Да, 10 первых по дате комедий)

2016-09-17 09:55 UTC, postgred commented on movies.rb
> +print_films(films.sort_by{ |film| film[:genre].include?("Camedy") }.sort_by { |film| film[:date] }.first(10))
А нет, просто магичски так совпало, что все что он выдал имеет в жанре Comedy

2016-09-17 10:08 UTC, zverok approved these changes

2016-09-17 10:13 UTC, merged