Task5
postgred/myrubycource pull request #4
Opened 2016-09-17 19:39 UTC by postgred

2016-09-17 20:23 UTC, zverok commented on movie.rb
> +    self.genre.include?(genre)
Лишний `self.`

2016-09-17 20:24 UTC, zverok commented on movies.rb
> +    @films.sort_by { |film| film.send(field) }
Кстати, тут кажется будет достаточно `.sort_by(&field)`, м?

2016-09-17 20:25 UTC, zverok commented on movies.rb
> +    end.flatten
`reduce` тут пригодится.

2016-09-17 20:27 UTC, zverok commented on movies.rb
> +  end
Этот метод должен быть, теоретически, в тыщу раз короче, не? Он же всё делает одинаково (`map.[flatten.].group_by`) для всех вариантов?..

2016-09-17 20:28 UTC, zverok requested changes

2016-09-17 20:34 UTC, postgred commented on movie.rb
> +    self.genre.include?(genre)
Не лишний, иначе он решит что genre это аргумент

2016-09-18 09:08 UTC, zverok commented on movie.rb
> +  end
Это можно сократить до 2 строчек:

1. ошибка если такого жанра вообще не бывает.
2. есть ли такой жанр у меня?

2016-09-18 09:17 UTC, zverok commented on movies.rb
> +    end
:+1: 
А теперь пара примеров для размышления:
* `filter(year: 1980..1990)`
* `filter(genre: /comedy/i)` (ну не помню, как там жанры пишутся, большими или маленькими буквами!)

Советы по реализации:
* добавить фильму метод `matches?(filter, value)`
* скорее всего у него будут две «ветки» — для полей-массивов (жанр, актёры) использовать `.include?` для остальных — прекрасный метод `===`

2016-09-18 09:19 UTC, zverok commented on movies.rb
> +    end
Обрати внимание, что две ветки `case` теперь почти совсем одинаковые ;) Кроме того, как берутся начальные значения. Может, это дело фильма вообще — отвечать на запрос типа `value_for_stats(:month)`, `value_for_stats(:director)` и т.д., внутре приводя всё в порядок? Такое и тестировать проще...

2016-09-18 09:22 UTC, zverok commented on demo.rb
> +end
Теперь отдельный `print_films` не нужен.
Если ты определишь фильму красивый `inspect` и `to_s`, то просто конструкции типа `p movies.all` и `puts movies.all` будут работать волшебно. 

Совет: `to_s` выводит скорее для красоты — что-то вроде того как сейчас `print_films` выводит, а `inspect` — скорее для отладки, чтобы видно было тип объекта и самое важное о нём, обычно как-то так: `#<Movie title (producer: foo, date: bar)>` — посмотри как встроенные классы выводятся в `p`, и как в `puts`

2016-09-18 09:23 UTC, zverok requested changes

2016-09-25 07:46 UTC, zverok commented on movie.rb
> +      send(filter).include?(value)
а какие случаи у нас теперь include? обслуживает? и будет ли это работать с filter(director: /coppola/i), м?

2016-09-25 07:48 UTC, zverok commented on movies.rb
> +    end
а тебе не кажется, что этот метод бы в Movie занести?

2016-09-25 07:50 UTC, zverok requested changes
Кроме оставленных замечаний, остальное очень ок - чисто, компактно, читабельно!

2016-09-25 15:12 UTC, zverok commented on movie.rb
> +    end
Тут достаточно всего _двух_ случаев:
* Если поле массив — нужно any?
* Если нет — достаточно всего одного `===` (не нужно создавать регексп, и не нужно лишних скобок как в строке 24). Потому что строки/числа оно тоже прекрасно сравнивает.

А вот привести год в разумную форму (= числовую) лучше прямо в initialize.

В целом, идея ж не в том, чтобы сделать «как понравится ментору». Идея в том, что Руби позволяет всё делать _очень_ компактно и гибко.

2016-09-25 15:12 UTC, zverok commented on movie.rb
> +    if send(filter).class == Array
Лучше `is_a?(Array)` (лучше читается)

2016-09-25 15:15 UTC, zverok commented on movie.rb
> +    end
Ага, всё стало немного проще, правда? :) Теперь упрощаем ещё раз: если а) у нас будет метод month и б) коллекции будет ок, что часть значений — nil — то отдельный метод `value_for_stats` вообще не будет нужен ;)

2016-09-25 15:17 UTC, zverok commented on movies.rb
> +    @films.map { |film| film.value_for_stats(field) }.compact.sort.group_by(&:itself).map { |key, value| [key, value.count ] }.to_h
...а кстати, коллекции и так норм, если вернётся `nil` (потому что ты разумно используешь `compact` :+1: ). То есть здесь уже можно просто `film.send(field)`, правда?.. Ну разве что flatten тут где-нибудь пригодится ещё, наверное :) И выражение на строки разбить для пущей читабельности.

2016-09-25 15:17 UTC, zverok requested changes
Ещё немножечко!!!

2016-09-26 10:38 UTC, zverok commented on movie.rb
> +    @date = params[:date].split('-')
Почему не Date?

2016-10-01 12:00 UTC, zverok requested changes
Остались мелочи. Но важные!

2016-10-01 12:00 UTC, zverok commented on movie.rb
> +    if send(filter).class == Array
`is_a?`

2016-10-01 12:00 UTC, zverok commented on movies.rb
> +    @films.map(&:genre).flatten.uniq
Лучше не вычислять каждый раз, а запомнить в переменной после первого вычисления (оператор `||=`), этот набор же не изменится, а считать его относительно долго.

2016-10-01 12:00 UTC, zverok commented on movie.rb
> +    @month = date[1]
Можно не хранить в переменной (в переменных мы храним то, что является исходными данными, т.е. невозможно вычислить из других данных — или, как сказано ниже, то что вычислять из других данных каждый раз дорого). Простенького метода хватило бы.

2016-10-01 12:00 UTC, zverok commented on movie.rb
> +    @duration = params[:stars].split(' ')[0].to_i
`.first` лучше читается (потому что подчёркивает, что нам нужен был именно первый элемент, а не «ну, с каким-то индексом»)
Но, кстати, можно упростить, потому что строка, начинающаяся с числа, и так бы преобразовалась: `"100 min".to_i # => 100`
И ещё кстати — тут по-моему опечатка (должно же быть `params[:duration]`, не?..), и рейтинг в результате нигде не хранится у нас...

2016-10-01 12:35 UTC, zverok approved these changes
:+1:

2016-10-01 19:06 UTC, merged