Task6
postgred/myrubycource pull request #5
Opened 2016-10-09 15:33 UTC by postgred

2016-10-14 09:42 UTC, zverok reviewed
В целом начало норм, я пару придирок оставил.
Идея в том, чтобы тестами чотко и красиво описать именно то, что в постановке задачи — и настолько читабельно, чтобы постановку задачи можно было по тестам легко считать.

PS: сорри, что комментирую в пятницу, а не в понедельник, залил ноутбук чаем, два дня был без него, а потом догонял всё упущенное :(

2016-10-14 09:42 UTC, zverok commented on spec/ancient_movie_spec.rb
> +  end
Лучше так:
Если для метода всего один тест:
```ruby
its(:to_s) { is_expected.to eq '....' }
```
(требует гема `rspec-its` дополнительно)
Если много:
```ruby
describe '#to_s' do
  # один тест
  # другой тест
end
```

2016-10-14 09:42 UTC, zverok commented on spec/netflix_spec.rb
> +      expect(netflix.show).not_to eq netflix.show
тестирование радномных методов не такая простая вещь :) этот тест легко может упасть, лучше что-нибудь типа `expect(10.times { netflix.show }.uniq.count).not_to eq 1` (тоже есть вероятность что все 10 раз случайность выберет один и тот же фильм, но меньше, чем 2 случайности выберут один фильм)

2016-10-23 10:17 UTC, zverok reviewed
Немножко комментов оставил. Спеки посмотрю чуть позже сегодня же.

2016-10-23 10:17 UTC, zverok commented on classic_movie.rb
> +    end
Сам себе жизнь усложняешь, в задании было количество фильмов этого режиссёра (т.е. чтобы по-прежнему была короткая строчка, но с дополнительной информацией — этот режиссёр настолько известен, что в топ-250 аж N его фильмов!)

2016-10-23 10:17 UTC, zverok commented on ancient_movie.rb
> +  def price
А не должно ли это быть константой, вместо метода, м?

2016-10-23 10:17 UTC, zverok commented on ancient_movie.rb
> +    :ancient
по-моему, это вполне можно вычислить из имени класса.

2016-10-23 10:17 UTC, zverok commented on movies.rb
> +    end
А вот бы эту логику в класс `Movie` перенести? Чтобы коллекция делала просто `Movie.create(fields, self)`, а остальное уже было делом `Movie` — объект какого класса оно создаст. Вроде логичнее.

2016-10-23 10:33 UTC, postgred commented on classic_movie.rb
> +    end
Нет, в задании сказано список фильмов)

2016-10-23 10:37 UTC, zverok commented on classic_movie.rb
> +    end
> ClassicMovie (1945-1968): «Название — классический фильм, режиссёр такой-то (ещё 10 его фильмов в спике)»

«ещё 10 его фильмов» — это пример вывода как раз и есть :)

2016-10-29 20:33 UTC, zverok requested changes

2016-10-29 20:33 UTC, zverok commented on classic_movie.rb
> +  end
учитывая зачем оно нужно, `@collection.filter(...).count - 1` было бы вполне достаточно ;)

2016-10-29 20:33 UTC, zverok commented on classic_movie.rb
> +  end
(идея в том, чтобы порождать как можно меньше промежуточных переменных и постепенных операций с ними; если бы нам правдо нужно было не кол-во, а список, я бы сказал что `@collection.filter(...) - [self]` лучше чем эти три строчки)

2016-10-29 20:33 UTC, zverok commented on movie.rb
> +    end
к слову, можно было так (не факт что это НАМНОГО лучше читается, но меньше повторения одного и того же):

``` ruby
case fields[:year].to_i
when 1900..1945
  AncientMovie
when 1946..1968
  ClassicMovie
when 1969..2000
  ModernMovie
when 2001..Time.new.year
  NewMovie
end.new(fields, collection)
```

2016-10-29 20:33 UTC, zverok commented on movies.rb
> +  end
На самом деле, всё тут немножко а) запутанно, и б) не выполняет поставленной цели. 
Во-первых, почему фильмы передаются в метод, а не используются те, которые в коллекции лежат?..
Во-вторых, «правильный» подход — это отсортировать фильмы в порядке `rand * stars`, а потом взять последний (прикинь, как это работает, и сообрази почему)

2016-10-29 20:33 UTC, zverok commented on netflix.rb
> +    raise NoMoney if money < movie.class::PRICE
а вот чтобы не писать это каждый раз, можно спрятать в метод `price` (определённый ОДИН раз в родительском Movie)

2016-10-29 20:33 UTC, zverok commented on netflix.rb
> +    self.start_time = Time.now
зачем при этом менять состояние самой коллекции? а если несколько пользователей из разных потоков используют класс `Netflix`, што будет?

2016-10-29 20:33 UTC, zverok commented on spec/collection_spec.rb
> +    end
Тебе не кажется, что все эти тесты ОЧЕНЬ повторяются? Мы не любим повторяться! Какой-нибудь вспомогательный метод наверное помог бы. Или просто можно попробовать вот так:
```ruby
expect(films.filter(title: 'The Terminator')).to not_be_empty.and all have_attributes(title: 'The Terminator')
```
(`not_be_empty` придётся определить)

2016-10-29 20:33 UTC, zverok commented on spec/theatre_spec.rb
> +      expect(filteres_films).to include(theatre.show("8:30").match(/(?<=Now showing: )[A-Za-z ]*/).to_s)
Тяжело так тестировать. Я бы сделал промежуточный метод (который возвращал бы не строчку, а реальный объект Movie, выбранный для показа), и тестировал бы а) какой Movie выбирается и б) что show использует именно его.

2016-10-29 20:33 UTC, zverok commented on theatre.rb
> +    end
а хорошо бы эту логику в константу вынести и использовать в обоих методах (filter_by_time и when), м?

2016-11-05 11:51 UTC, zverok requested changes

2016-11-05 11:51 UTC, zverok commented on classic_movie.rb
> +    movies = @collection.filter(producer: producer).count - 1
а переменная `movies` тут зачем? и, кстати, такой метод лучше сделать приватным.

2016-11-05 11:51 UTC, zverok commented on netflix.rb
> +    raise NoMoney if money < movie.price
Лучше добавить ошибке осмысленное сообщение (типа «для просмотра %moviename% надо %money%, а у вас на счету %othermoney%»)

2016-11-05 11:51 UTC, zverok commented on netflix.rb
> +    filter(title: title).first.price
А если фильм не нашёлся?

2016-11-05 11:51 UTC, zverok commented on spec/ancient_movie_spec.rb
> +  its(:to_s) { should eq "#{movie.title} - старый фильм (#{movie.year} год)" }
В тесте лучше явно прописывать ожидаемое значение (иначе, учитывая что здесь повторяется код самого метода, может потеряться какая-нибудь дикая ошибка — напр `year` всегда `nil`, тест пройдёт, но в описании фильма на самом-то деле написано `( год)`)

2016-11-05 11:51 UTC, zverok commented on spec/collection_spec.rb
> +    end
Можно аккуратнее — через `context`:
```ruby
contex 'when Ancient' do
  subject { films.filter(year: 1900..1945) }
  it { is_expected.to all be_an AncientMovie }
end
```
Потом замечаем, что 4 контекста получаются идентичными, вспоминаем принцип DRY и используем shared_context ;)

2016-11-05 11:51 UTC, zverok commented on spec/netflix_spec.rb
> +      expect(netflix.show({producer: 'Oliver Stone', period: :modern})).to eq "Now showing: #{netflix.filter(producer: 'Oliver Stone', period: :modern).first.to_s}"
Фигурные скобочке в вызове `show` — лишние, Ruby и так поймёт :)

2016-11-05 11:51 UTC, zverok commented on spec/theatre_spec.rb
> +      theatre.show
А что тестирует этот метод? Если будет ли вызван `random_by_stars`, то лучше так и выразиться (`expect ... to receive`)

2016-11-05 11:51 UTC, zverok commented on theatre.rb
> +  end
А что если логику этих двух методов положить в одну общую константу, и в обоих методах её использовать? А то сейчас адское дублирование получается.

2016-11-06 15:20 UTC, zverok requested changes

2016-11-06 15:20 UTC, zverok commented on spec/ancient_movie_spec.rb
> +  before { @films = MovieCollection.new('./spec/movies.txt') }
`let(:films)` вместо `befre { @films ... }` ;)

2016-11-06 15:20 UTC, zverok commented on spec/collection_spec.rb
> +    it_should_behave_like 'movie type', 2001..Time.new.year, NewMovie
Воот!

2016-11-06 15:20 UTC, zverok commented on spec/netflix_spec.rb
> +      expect(netflix.money).to eq 20
Есть отличный матчер для такого случая:

```ruby
expect { netflix.pay(20) }.to change(netflix, :money).from(0).to(20)
```

Смысл наших ожиданий лучше показывает.

2016-11-06 15:20 UTC, zverok commented on theatre.rb
> +    "С #{time.first} до #{time.last}"
А если не нашлось время когда его показывают? (И тест бы на этот случай)

2016-11-06 15:20 UTC, zverok commented on theatre.rb
> +    end
Тебе не кажется, что тут всё ещё дублирование кода? `when MORNING` → `FILTERS[MORNING]`? Которое, кстати, порождает забавный баг (всмотрись в строки 41-42)

2016-11-13 10:59 UTC, zverok requested changes
Остались некоторые замечания к спекам. Мне кажется — полезные.

2016-11-13 10:59 UTC, zverok commented on exeptions.rb
> +  end
Кстати (но это информация к размышлению, а не требование изменить код) в таких случаях имеет смысл сохранять и структурированные данные в эксепшене (т.е. title, price, money по отдельности, раз уж они известны в момент создания). Тогда клиент сможет сделать как-то так:
```ruby
# ...
rescue NoMoney => e
  puts "Совсем по-другому отформатированное сообщение, что #{price} > #{money}"
end

2016-11-13 10:59 UTC, zverok commented on spec/netflix_spec.rb
> +      end
Вот эти 4 одинаковых теста очень некрасивые. Можно существенно лучше:
1. вынести `pay` в `before`
2. в самом тесте использовать матчер `change` — тогда они будут однострочные
```ruby
expect { netflix.show(period: :new) }.to change(netflix, :money).by(-5)
```
↑ теперь тут чётко написано, что именно мы тестируем!

Помни про DRY! 4 совершенно одинаковых куска кода — это всегда признак что мы делаем что-то не так.

2016-11-13 10:59 UTC, zverok commented on spec/theatre_spec.rb
> +      expect(hours.map { |hour| theatre.filter_by_time("#{hour}:00") }.flatten.map(&:class)).to all eq AncientMovie
В идеале, любой тест должен БЫСТРО читаться, сразу передавая смысл. Этот тест требованию не соответствует (попробуй это своими словами пересказать, что в этой строчке). Чисто по логике если, то...
1. ожидается, что в любой час с 8..11
2. показываемый фильм будет...
3. соответствовать фильтру «период только ancient»

Попробуем записать это на воображаемом небесном руби, максимально коротко и читабельно:
```ruby
expect(8..11).to all show_movie_matching(period: :ancient)
# или, чуть по-другому, но вроде всё равно читабельно
expect(movies_at(8..11)).to all match(period: :ancient)
```
Вариант а) можно реализовать с помощью собственного матчера, но это будет излишне сложно.
А вот вариант б) — просто с помощью определения маленького helper-метода `movies_at` + записывания матчера как `ba_match` — немножко безграмотно, зато вызовет метод фильма `match` и всё будет хорошо.

2016-11-13 10:59 UTC, zverok commented on theatre.rb
> +    rescue
rescue без указания чего именно ожидаешь — довольно дурной тон (ты так можешь пропустить вообще какую-нибудь несвязанную ошибку, типа «disk is full, не могу прочитать movies.txt»). Ну и управление логикой именно через rescue — может быть не самая хорошая идея, оно всё-таки для перехвата Исключительных ситуаций.

2016-11-13 15:53 UTC, zverok approved these changes

2016-11-13 16:05 UTC, merged