Task7
postgred/myrubycource pull request #6
Opened 2016-11-20 09:38 UTC by postgred

2016-11-20 14:06 UTC, zverok requested changes
Не, с подключаемым модулем пока получилось кривовато, надо думать! (ключевые слова: include vs extend)

2016-11-20 14:06 UTC, zverok commented on cashbox.rb
> +      end
мы кажется уже обсуждали такую ситуацию: лучше в начале метода проверять все предусловия и вылетать если что, а дальше уже не думать о них.

2016-11-20 14:06 UTC, zverok commented on netflix.rb
> +      @cashbox = create_cashbox(File.read('./cashbox_netflix.txt'))
Не, если уж мы подключаем модуль, обеспечивающий функциональность кассы, мы стараемся быть от него независимыми — все переменные, какие ему нужны, пусть создаёт сам, с т.з. вызывающего класса всё должно «просто работать»

2016-11-20 14:06 UTC, zverok commented on netflix.rb
> +      update_cashbox
А почему приходится вызвать два разных метода, чтобы кассу пополнить?

2016-11-20 14:06 UTC, zverok commented on netflix.rb
> +      File.open('./cashbox_netflix.txt', 'w') do |file|
А зачем вообще вся эта возня с файлами? Чтобы выполнить задачу «у всех нетфликсов одна общая касса»? Нужно проще!

2016-11-20 14:06 UTC, zverok commented on spec/cashbox_spec.rb
> +include Theaters::Cashbox
Для тестирования модулей, лучше инклюдить их не в общее пространство имён, а в маленький класс-для-тестирования.

2016-11-20 14:06 UTC, zverok commented on movies.rb
> +    include Enumerable
Тестов добавил?

2016-11-20 15:23 UTC, postgred commented on netflix.rb
> +      File.open('./cashbox_netflix.txt', 'w') do |file|
А куда проще то? Сделать @@money?

2016-11-21 07:59 UTC, zverok commented on netflix.rb
> +      File.open('./cashbox_netflix.txt', 'w') do |file|
Не совсем `@@`-переменные — дурной тон, почти не используются (из-за их неочевидного поведения). Зато можно использовать `@`-переменные объекта Netflix (а это тоже объект класса Class), а включив в него модуль через `extend` — получим класс с одной общей кассой.

2016-11-27 11:13 UTC, zverok requested changes

2016-11-27 11:13 UTC, zverok commented on spec/cashbox_spec.rb
> +    expect { test_class.refill(5) }.to change{ test_class.money.fractional }.from(0).to(5)
проверь, что будет, если сделать 2 refill подряд:
```ruby
expect { test_class.refill(5); test_class.refill(10) }.to # ???
```

Вероятно, будешь удивлён ;)

2016-11-27 11:13 UTC, zverok commented on spec/cashbox_spec.rb
> +    context 'Bank can take the money' do
контексты обычно называют, начиная со слова `when` (в сумме, всё вместе — context и it'ы в нём должно читаться как длинная фраза, rspec же её выдаёт при ошибках): типа `context "when money are taken by bank"` -> `it "should be successfully taken"`

2016-11-27 11:13 UTC, zverok commented on spec/netflix_spec.rb
> +      netflix2 = Theaters::Netflix.new
лучше его отдельным `let`-ом создать.

2016-11-27 11:13 UTC, zverok commented on spec/netflix_spec.rb
> +      expect(netflix.cash).to eq netflix2.cash
...и проверить, что укладывание денег в два разных кинотеатра одинаково влияет на кассу.

2016-12-25 11:47 UTC, zverok approved these changes

2016-12-25 11:47 UTC, zverok commented on cashbox.rb
> +      @cashbox = Money.new(cashbox.fractional + money, 'USD')
тебе не кажется, что здесь чище выглядел бы вот такой код: `cashbox += Money.new(amount, 'USD')`, м?

2016-12-25 11:47 UTC, zverok commented on spec/netflix_spec.rb
> +      expect { netflix.pay(20) }.to change { netflix2.cash.fractional }.from(netflix.cash.fractional).to(netflix.cash.fractional + 20)
у матчера есть вариант `expect {}... to change {...}.by(20)`, к слову.

2016-12-25 18:25 UTC, merged