Task9
postgred/myrubycource pull request #8
Opened 2016-12-30 09:54 UTC by postgred

2016-12-30 18:02 UTC, zverok requested changes

2016-12-30 18:02 UTC, zverok commented on movies.rb
> +        line[:collection] = self
Э. Дык вся прелесть виртуса в том, что он эти штуки (преобразования) позволяет описать красиво, и выполняет автоматом. Теперь понятно, почему ты не впечатлился :)

2016-12-31 12:19 UTC, zverok requested changes

2016-12-31 12:19 UTC, zverok commented on movie.rb
> +      attribute :date, DateArray
А почему `DateArray` его называть, тут же не массив дат?.. и кстати просто `Date` тоже вполне может работать, мне кажется.

2016-12-31 12:19 UTC, zverok commented on movie.rb
> +      attribute :duration, Duration, strict: true
Зачем новый тип? `Fixnum` бы хватило.

2016-12-31 12:19 UTC, zverok commented on movie_by_genre.rb
> +  end
Да, вполне разумно. Только определять метод у _всего класса_ нехорошо (тогда, если у тебя есть две коллекции, созданные из разных источников данных с разными жанрами, вызов на первой `by_genre` определит и у второй все те же жанры). `define_singleton_method` зато создаст метод _только_ у этого объекта.

2016-12-31 12:19 UTC, zverok commented on movies.rb
> +        Movie.create(line.to_h)
Почему не `line.to_h.merge(collection: self)`?

2016-12-31 12:19 UTC, zverok commented on spec/netflix_spec.rb
> +          expect(netflix.by_country.send(country)).to all from_country(country)
На самом деле можно было обойтись без лишнего матчера :) `.to all have_attributes(country: 'Canada')`

2016-12-31 12:19 UTC, zverok commented on movie_by_country.rb
> +  def method_missing(name, *args, &block)
когда делаешь `method_missing`, неплохо бы выбросить «явные ошибки» (т.е. вызовы типа `by_country.usa(foo: 'bar')` или `by_country.usa = false`)

2016-12-31 12:36 UTC, postgred commented on movie.rb
> +      attribute :duration, Duration, strict: true
Fixnum выдает ошибку, что не может сконвертить строку в число

2016-12-31 12:40 UTC, zverok commented on movie.rb
> +      attribute :duration, Duration, strict: true
А, есть такое, да :(

2017-01-07 20:33 UTC, zverok requested changes
Ты большой молодец. Но надо лучше :)

2017-01-07 20:33 UTC, zverok commented on spec/theatre_spec.rb
> +    end
«что мы описываем?» — какой зал получается, когда мы вызвали DSL; таким образом, тут разумнее всего сделать:
* describe '#hall'
* subject — какой зал получился
* остальное — маленькие тесты на subject

2017-01-07 20:33 UTC, zverok commented on spec/theatre_spec.rb
> +    context 'create period' do
тут аналогично:
* describe '#period'
* subject — созданный период
* остальное — короткие тесты на чо получилось

2017-01-07 20:33 UTC, zverok commented on spec/theatre_spec.rb
> +      end
если бы период у нас был subject-ом, то тут можно было бы писать просто `its(:time) { is_expected... }`

2017-01-07 20:33 UTC, zverok commented on theatre.rb
> +      periods.combination(2).any? { |p1, p2| p1.intersects?(p2) }
можно проще, хотя тут уже всё на месте! то есть нам нужно что, гляди: (существующие периоды + этот период) → любая пара пересекается?(по залам и времени).
То есть в руби-коде должно бы быть написано что-то типа вообще
```ruby
[*@periods, period].any? { |p1, p2| p1.intersects?(p2) } # а уже intersects проверяет И залы И время
```
м?

2017-01-07 20:33 UTC, zverok commented on theatre_hall.rb
> +  class TheatreHall
может его внутрь класса спрятать? `class Theatre::Hall`

2017-01-07 20:33 UTC, zverok commented on theatre_hall.rb
> +  class TheatreHall
Кстати, залы у нас совсем простые, их можно от `Struct` унаследовать.

2017-01-07 20:33 UTC, zverok commented on theatre_period.rb
> +  class TheatrePeriod
Аналогичные замечания, как и к залам.

2017-01-07 20:33 UTC, zverok commented on theatre_period.rb
> +      end
Всё ещё замусориваем класс Period?.. Грусно!

2017-01-08 19:56 UTC, zverok approved these changes
:+1: 
Отлично.

2017-01-08 19:56 UTC, zverok commented on theatre_period.rb
> +        end
Мне кажется, можно лучше. `halls_intersected?(period2) && time_intersected?(period2)` м?

2017-01-08 19:56 UTC, zverok commented on theatre.rb
> +      @periods ||= []
Зачем тут `||`? Это ж `initialize`, они ещё точно пустые.

2017-01-08 19:56 UTC, zverok commented on spec/theatre_spec.rb
> +      end
Тут можно (хотя и не обязательно) сделать так:

```ruby
let(:dsl) {
  Theaters::Theatre.new do
     period '10:00'..'11:00' do
       hall :red
     end

     period '10:00'..'10:30' do
       hall :red
     end
  end
}

it '....' do
 expect { dsl } .to raise_error(InvalidPeriod)
end
```
(и во всех примерах вынести этот `dsl` вызов в `let`, многое станет аккуратнее)

2017-01-09 02:42 UTC, merged