Task10
postgred/myrubycource pull request #9
Opened 2017-01-10 20:25 UTC by postgred

2017-01-13 11:54 UTC, zverok reviewed
Очень прилично! Можно было бы больше спек на отдельные частные методы клиента (его так было бы проще разрабатывать), но в принципе и так норм.

2017-01-13 11:54 UTC, zverok commented on imdb_client.rb
> +  Tmdb::Api.key('66dd6d4dec26548c02b70560ec20020f')
Ключи и пароли не хранят в коде и репозиториях :) Обычно кладут в конфиги, конфиги — в .gitignore, а в репозиторий какой-нибудь пустой семпл конфига (`config.sample.yml`) и объяснения как всё настроить. Есть впрочем и более сложные/современные варианты (`.env`). Но точно не в код.

2017-01-13 11:54 UTC, zverok commented on imdb_client.rb
> +    File.open('./budgets.yml', 'w') { |f| f.write(budgets.to_yaml) }
В современном руби есть `File.write` ;)

2017-01-13 11:54 UTC, zverok commented on imdb_client.rb
> +class IMDBClient
К слову, если уж ты тут смешал парсинг данных из IMDB и TMDB, то модуль называется неверно.

2017-01-14 09:43 UTC, postgred commented on imdb_client.rb
> +  Tmdb::Api.key('66dd6d4dec26548c02b70560ec20020f')
Да, знаю, но мне было лень)

2017-01-17 14:25 UTC, zverok requested changes
И ещё важный момент: _зачем_ мы всё это делали? У нас же была, в общем, понятная библиотека «работает с фильмами и их коллекциями» — но при этом новая функциональность никак с ней не пересекается, а? Она как-то отдельно лежит. А хорошо бы у нас появилось на самом деле что-то типа:
* загружалка доп.данных
* `Movie#budget` — выдаёт бюджет или ошибку «бюджеты не загружены.» (и то же для других данных)
* рендерилка фильмов в HTML
* MovieCollection#render

Тогда это всё обрело бы какой-то смысл, м?

2017-01-17 14:25 UTC, zverok commented on tmdb_client.rb
> +class TMDBClient
Это что за странный артефакт? :)

2017-01-17 14:25 UTC, zverok commented on spec/support/vcr_setup.rb
> +end
В принципе, такие штуки нормально и в основном spec_helper оставлять, чтобы не плодить сущности. Решение с support/ оно для больших проектов, где spec_helper раздувается в стопицот раз. (Можно не менять уже, just sayin')

2017-01-17 14:25 UTC, zverok commented on spec/spec_helper.rb
>  require_relative './matchers.rb'
...если уж у тебя есть папка support/ — матчеры лучше туда (чтобы не путались между файлами с тестами)

2017-01-17 14:25 UTC, zverok commented on mdb_client.rb
> +  Tmdb::Api.key(YAML::load(File.read('config.yml'))['key'])
Длинное рассуждение про этот класс:

1) Надо понимать, что объём задания небольшой, и кода получилось немного и вполне читабельного, поэтому можно оставить и так. А можно обратить внимание вот на что:
2) Тестируемость: когда есть класс/метод, выполняющий очень длительную операцию на огромной куче повторяющихся элементов, зачастую лучше протестировать:
* отдельно работу с одним элементом (то есть тест на парсинг одного кина, из imdb, из tmdb) — можно аккуратно протестировать и отладить
* отдельно — что общий метод вызовет парсинг фильма ровно столько раз (и с теми айдишниками), с которыми мы ожидаем.
3) Контролируемость. Для таких классов (которые выполняют долгую работу) лучше не прятать эту работу за `||=`, а наоборот дать юзеру контроль за ней:
```ruby
client.movies_list # => nil
client.load_list!(progress: false) # может я не хочу прогресс-бар!
client.movies_list # => [....]
client.load_budgets(cache: 'budgets2.yml') # грузит из файла; если файла нету — то из инета, и сохраняет в файл
client.load_budgets(cache: false) # всегда грузит из инета, и никогда не сохраняет в файл!
``` 

м?

2017-01-17 14:36 UTC, postgred commented on tmdb_client.rb
> +class TMDBClient
The Movie Data Base :)

2017-01-17 14:45 UTC, zverok commented on tmdb_client.rb
> +class TMDBClient
Ну я так и понял, но оно ж пустое.

2017-01-27 19:10 UTC, merged